import Header from "@/components/Header";
import "../styles/globals.scss";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Service des equivalence administraties et titres",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
